@startuml
class LayerRenderChanger {

RendererGroundDetector --> "renderChanger" LayerRenderChanger
LayerRenderChanger --> "invMesh" SpriteRenderer
LayerRenderChanger --> "unitEntity" UnitEntity
@enduml
