@startuml
class InfoUnit {
    + SetUnit(entity:UnitEntity, movementData:UnitMovementData) : void
}
MonoBehaviour <|-- InfoUnit
InfoUnit --> "meleeAttackGO" GameObject
InfoUnit --> "meleeAttackText" TextMeshProUGUI
InfoUnit --> "movementGO" GameObject
InfoUnit --> "movementText" TextMeshProUGUI
InfoUnit --> "unitProfileGO" GameObject
InfoUnit --> "enemyProfileGO" GameObject
@enduml
