name: Generate UML Diagrams

on:
  push:
    paths:
      - '**/*.cs'
      - '.github/workflows/generate-uml.yml'
  workflow_dispatch:

jobs:
  uml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install UML generator CLI
        run: dotnet tool install --global PlantUmlClassDiagramGenerator

      - name: Generate PlantUML files (all-in-one)
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          puml-gen Assets/Scripts UML \
            -dir \
            -public \
            -createAssociation \
            -allInOne

      # ← Aquí empiezan los pasos nuevos
      - name: Install Python & dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install networkx

      - name: Split UML into components
        run: python3 scripts/split_uml.py

      - name: Render UML component images
        uses: holowinski/plantuml-github-action@main
        with:
          args: '-tpng UML/components/*.puml'
      # ← Aquí terminan los pasos nuevos

      - name: Commit UML diagrams
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'chore: update UML diagrams'
